#!/bin/bash
openssl genrsa -out tls-assets/apiserver-key.pem 2048
openssl req -new -key tls-assets/apiserver-key.pem -out tls-assets/apiserver.csr -subj "/CN=kube-apiserver" -config tls-assets/openssl.cnf
openssl x509 -req -in tls-assets/apiserver.csr -CA tls-assets/ca.pem -CAkey tls-assets/ca-key.pem -CAcreateserial -out tls-assets/apiserver.pem -days 365 -extensions v3_req -extfile tls-assets/openssl.cnf