apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    # insecure-skip-tls-verify: true
    certificate-authority: ${cwd}/tls-assets/ca.pem
    server: https://${master_ip}:${api_secure_port}
  name: ${cluster_name}
users:
- name: admin
  user:
    client-certificate: ${cwd}/tls-assets/apiserver.pem
    client-key: ${cwd}/tls-assets/apiserver-key.pem
    # token: ${token}
contexts:
- context:
    cluster: ${cluster_name}
    user: admin
  name: ${cluster_name}
current-context: ${cluster_name}

