#!/bin/bash
# based on  https://github.com/pires/kubernetes-vagrant-coreos-cluster
# [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
[ -n "$1" ] && until curl -o /dev/null -sf ${1}; do sleep 1 && echo .; done;
exit $?

